admin/urls.py
from django.conf.urls import url
from rest_framework.routers import DefaultRouter

import admin.views as views

urlpatterns = [
    url(r'^$', views.index, name='admin-index'),

    url(r'^confirm/$', views.confirm_overview, name='admin-confirm'),
    url(r'^attest/$', views.attest_overview, name='admin-attest'),
    url(r'^pay/$', views.pay_overview, name='admin-pay'),
    url(r'^account/$', views.account_overview, name='admin-account'),

    url(r'^expense/(?P<pk>\d+)/verification/edit/$', views.edit_expense_verification, name='admin-expense-edit-verification'),
    url(r'^expense/(?P<expense_pk>\d+)/verification/$', views.set_verification, name='admin-expense-verification'),
    url(r'^expense/(?P<pk>\d+)/confirm/$', views.confirm_expense, name='admin-expense-confirm'),

    url(r'^invoice/(?P<invoice_pk>\d+)/verification/$', views.invoice_set_verification, name='admin-invoice-verification'),

    url(r'^expense-part/(?P<pk>\d+)/attest/$', views.attest_expense_part, name='admin-expensepart-attest'),
    url(r'^invoice-part/(?P<pk>\d+)/attest/$', views.attest_invoice_part, name='admin-invoicepart-attest'),

    url(r'^expenses/$', views.expense_overview, name='admin-expense-overview'),
    url(r'^invoices/$', views.invoice_overview, name='admin-invoice-overview'),
    url(r'^invoices/(?P<pk>\d+)/pay$', views.invoice_pay, name='admin-invoice-pay'),
    url(r'^verifications/$', views.search_verification, name='admin-search-verification'),
    url(r'^verifications/search/$', views.search_verification_response, name='admin-search-verification-api'),
    url(r'^verifications/list$', views.list_verification, name='admin-list-verification'),
    url(r'^users/$', views.user_overview, name='admin-user-overview'),
]

cashflow/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from cashflow import settings
from expenses import views
from .authviews import login, login_with_token, logout

urlpatterns = [
    url(r'^$', views.index, name='expenses-index'),
    url(r'^login/$', login, name='login'),
    url(r'^login/(?P<token>.+)/$', login_with_token, name='login_with_token'),
    url(r'^logout/', logout, name='logout'),
    url(r'^admin/', include("admin.urls")),
    url(r'^admin/django/', include(admin.site.urls)),
    url(r'^expenses/', include("expenses.urls")),
    url(r'^invoices/', include("invoices.urls")),
    url(r'^stats/', include("stats.urls")),
    url(r'^users/', include("users.urls")),
    url(r'^api/files/', include("file_api.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

expenses/urls.py
from django.conf.urls import url
from rest_framework.routers import DefaultRouter

import expenses.api_views.accounting as accounting_api
import expenses.api_views.attest as attest_api
import expenses.api_views.comment as comment_api
import expenses.api_views.expense as expense_api
import expenses.api_views.file as file_api
import expenses.api_views.misc as misc_api
import expenses.api_views.pay as pay_api
import expenses.api_views.user as user_api
import expenses.views as views

router = DefaultRouter()
router.register('expense',  expense_api.ExpenseViewSet, base_name='Expense')
router.register('payment', pay_api.PaymentViewSet, base_name='Payment')
router.register('comment', comment_api.CommentViewSet, base_name='Comment')
router.register('user', user_api.UserViewSet, base_name='User')
router.register('attest', attest_api.AttestViewSet, base_name='Attest')
router.register('accounting', accounting_api.AccountingViewSet, base_name='Accounting')
router.register('file', file_api.FileViewSet, base_name='File')
api_urlpatterns = router.urls

api_urlpatterns.append(url(r'^firebase_instance_id/$', misc_api.set_firebase_instance_id))
api_urlpatterns.append(url(r'^login/(.*)/$', misc_api.login, name='expenses-api-login'))
api_urlpatterns.append(url(r'^logout/$', misc_api.logout))

urlpatterns = [
    url(r'^new/$', views.new_expense, name='expenses-new'),
    url(r'^new/confirmation/(?P<pk>\d+)/$', views.expense_new_confirmation, name='expenses-new-confirmation'),
    url(r'^(?P<pk>\d+)/$', views.get_expense, name='expenses-show'),
    url(r'^(?P<pk>\d+)/edit/$', views.edit_expense, name='expenses-edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.delete_expense, name='expenses-delete'),
    url(r'^(?P<expense_pk>\d+)/comment/$', views.new_comment, name='expenses-comment'),
    
    url(r'^api/payment/new/$', views.api_new_payment, name='expenses-api-payment-new'),
    url(r'^payment/new/$', views.new_payment, name='expenses-payment-new'),
    url(r'^payment/(?P<pk>\d+)/$', views.get_payment, name='expenses-payment'),
]

expenses/models.py
import re

import requests
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.forms.models import model_to_dict
from django.template.loader import render_to_string
from datetime import date, datetime
        
from cashflow import dauth
from cashflow import settings
from invoices.models import *

"""

Defines all the models of the app.

"""

"""
BankAccount represents an actual bank account owned by the organisation.
This is a real bank account like one on Handelsbanken or another bank.
"""
class BankAccount(models.Model):
    name = models.TextField()

    # Return a string representation of the bank account
    def __str__(self):
        return self.name

    # Return a unicode representation of the bank account
    def __unicode__(self):
        return self.name

    # Creates a dict from the model
    def to_dict(self):
        return model_to_dict(self)



"""
A profile is attached to each user to be able to store more information
and relations with it.
"""
class Profile(models.Model):
    # The relation to the original django user
    user = models.OneToOneField(User)

    # Represents a bank account owned by the user
    bank_account = models.CharField(max_length=13, blank=True)
    
    sorting_number = models.CharField(max_length=6, blank=True)
    bank_name = models.CharField(max_length=30, blank=True)
    default_account = models.ForeignKey(BankAccount, blank=True, null=True)
    firebase_instance_id = models.TextField(blank=True)

    # Return a string representation of the user
    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

    # Return a unicode representation of the user
    def __unicode__(self):
        return self.user.first_name + " " + self.user.last_name

    # Creates a dict from the model
    def to_dict(self):
        person_dict = model_to_dict(self)
        person_dict['username'] = self.user.username
        person_dict['first_name'] = self.user.first_name
        person_dict['last_name'] = self.user.last_name
        person_dict['bank_info']['bank_account'] = self.bank_account
        person_dict['bank_info']['sorting_number'] = self.sorting_number
        person_dict['bank_info']['bank_name'] = self.bank_name
        if self.default_account is not None:
            person_dict['default_account'] = self.default_account.to_dict()
        else:
            person_dict['default_account'] = None
        del person_dict['user']
        del person_dict['id']
        return person_dict

    # Creates and returns an object with the user's properties
    def user_dict(self):
        return {
            'id': self.user.id,
            'username': self.user.username,
            'first_name': self.user.first_name,
            'last_name': self.user.last_name,
            'email': self.user.email,
            'bank_info': {
                'bank_account': self.bank_account,
                'sorting_number': self.sorting_number,
                'bank_name': self.bank_name
            }
        }

    # Returns a list of the committees that the user may attest
    def may_attest(self, expense_part=None):
        may_attest = []
        for permission in dauth.get_permissions(self.user):
            if permission.startswith("attest-"):
                may_attest.append(permission[len("attest-"):].lower())
        if expense_part == None:
            return may_attest
        return expense_part.committee_name.lower() in may_attest

    # Returns a list of the committees that the user may pay for
    def may_pay(self):
        return 'pay' in dauth.get_permissions(self.user)

    # Returns a list of the committees that the user may pay for
    def may_confirm(self):
        return 'confirm' in dauth.get_permissions(self.user)

    # Returns a list of the committees that the user may account for
    def may_account(self, expense=None, invoice=None):
        if '*' in dauth.get_permissions(self.user) and (not expense == None or not invoice == None):
            return True

        may_account = []
        for permission in dauth.get_permissions(self.user):
            if permission.startswith("accounting-"):
                may_account.append(permission[len("accounting-"):].lower())
        if expense == None and invoice == None:
            return may_account

        if expense != None:
            for ep in expense.expensepart_set.all():
                if ep.committee_name.lower() in may_account:
                    return True
        else:
            for ip in invoice.invoicepart_set.all():
                if ip.committee_name.lower() in may_account:
                    return True
        return False

    def may_delete(self, expense):
        if expense.reimbursement:
            return False

        if expense.owner.user.username == self.user.username: return True
        for expense_part in expense.expensepart_set.all():
            if self.may_attest(expense_part):
                return True
        return False

    def may_be_viewed_by(self, user):
        return user.username == self.user.username or user.profile.is_admin()

    def may_view_expense(self, expense):
        if expense.owner.user.username == self.user.username or self.may_pay():
            return True
        for committee in expense.committees():
            if committee.lower() in self.may_account() or committee.lower() in self.may_attest():
                return True

        return False

    def may_view_invoice(self, invoice):
        if invoice.owner.user.username == self.user.username or self.may_pay():
            return True
        for committee in invoice.committees():
            if committee.lower() in self.may_account() or committee.lower() in self.may_attest():
                return True

        return False

    def is_admin(self):
        return self.may_attest() or self.may_pay() or self.may_confirm() or self.may_account()


# Based of https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()



"""
Represents a payment from a chapter account to a member.
"""
class Payment(models.Model):
    date = models.DateField(auto_now_add=True)
    payer = models.ForeignKey(Profile, related_name='payer')
    receiver = models.ForeignKey(Profile, related_name='receiver')
    account = models.ForeignKey(BankAccount)

    # Return a string representation of the payment
    def __str__(self):
        return str(self.amount) + " kr on " + str(self.date) + " transferred by " + self.payer.__str__()

    # Return a unicode representation of the payment
    def __unicode__(self):
        return str(self.amount) + " kr on " + str(self.date) + " transferred by " + self.payer.__unicode__()

    # Return a dict from the model
    def to_dict(self):
        payment = model_to_dict(self)
        payment['payer'] = self.payer.user_dict()
        payment['receiver'] = self.receiver.user_dict()
        payment['account'] = self.account.to_dict()
        payment['tag'] = self.tag()
        payment['amount'] = self.amount()
        return payment

    # Returns the total amount of the payment
    def amount(self):
        total = 0
        for expense in Expense.objects.filter(reimbursement=self):
            total += expense.total_amount()
        return total

    # Returns the payment tag, which makes the payment identifiable in the bank
    def tag(self):
        return "Data" + str(self.id)



"""
Represents an expense. An expense contains expense parts and information 
about the expense.
"""
class Expense(models.Model):
    created_date = models.DateField(auto_now_add=True)
    expense_date = models.DateField()
    confirmed_by = models.ForeignKey(User, blank=True, null=True)
    confirmed_at = models.DateField(blank=True, null=True, default=None)
    owner = models.ForeignKey(Profile)
    description = models.TextField()
    reimbursement = models.ForeignKey(Payment, blank=True, null=True)
    verification = models.CharField(max_length=7, blank=True)

    # Returns a string representation of the expense
    def __str__(self):
        return self.description

    # Returns a unicode representation of the expense
    def __unicode__(self):
        return self.description

    # Returns a json dict from the expense
    def __repr__(self):
        return str(self.to_dict())

    def status(self):
        if self.verification: return "Bokförd som " + str(self.verification)
        if self.reimbursement: return "Utbetald"
        if self.is_attested() and self.confirmed_by: return "Inväntar utbetalning"
        if self.is_attested() and not self.confirmed_by: return "Attesterad men inte i pärmen"
        if not self.is_attested() and self.confirmed_by: return "Inte attesterad men i pärmen"
        return "Inte attesterad"

    # Return the total amount of the expense parts
    def total_amount(self):
        total = 0
        for part in self.expensepart_set.all():
            total += part.amount
        return total

    # Returns the committees belonging to the expense as a list [{ committee_name: 'Name' }, ...]
    def committees(self):
        return self.expensepart_set.order_by('committee_name').values('committee_name').distinct()

    # Returns the committees belonging to the expense as a list [{ committee_name: 'Name' }, ...]
    def is_attested(self):
        print(self.expensepart_set.filter(attested_by__isnull=True).count())
        return self.expensepart_set.filter(attested_by__isnull=True).count() == 0

    # Returns a dict representation of the model
    def to_dict(self):
        exp = model_to_dict(self)

templates/expenses/confirmation.html
{% extends "../detail.html" %}
{% load widget_tweaks %}

{% block title %}Sätt in kvittot i pärmen{% endblock %}

{% block full_content %}
    <div>
        <p>Sätt in ditt kvitto i kvittopärmen i META på en <u><a href="/static/kvittomall.pdf">kvittomall</a></u>.</p>
        <p>Märk kvittomallen med id:t <b>{{ expense.pk }}</b>. Du hittar det på din sida igen om du glömmer bort det.</p>
        <p>Kvittopärmen <b>ska</b> vara sorterad efter Cashflow-ID i stigande ordning. Om du sätter in ditt kvitto fel riskerar du att det inte blir utbetalt.</p>
        <a href="{% url "expenses-show" expense.pk %}" class="button primary-action btn-color theme-color" style="color:#fff">Gå vidare</a>
    </div>
{% endblock %}

templates/expenses/delete.html
{% extends "../detail.html" %}
{% load widget_tweaks %}

{% block title %}Ta bort kvitto{% endblock %}

{% block full_content %}
<p>Är du helt säker på att du vill ta bort kvittot "{{ expense.description }}"? Detta går inte att ångra!</p>
<form method="POST" action="">
    {% csrf_token %}
    <div class="form-group">
        <div class="col-sm-offset-10 col-sm-2">
            <button type="submit" class="button primary-action btn-color">Ta bort kvittot</button>
        </div>
    </div>
</form>
<div class="clearfix"></div>
{% endblock %}

templates/expenses/edit-verification.html
{% extends "../detail.html" %}
{% load widget_tweaks %}

{% block title %}Ändra verifikation{% endblock %}

{% block full_content %}
<div id="form">
    <form method="POST" action="" class="form-horizontal" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>Kvittodelar</h2>
        <table>
            <thead>
                <tr>
                    <th>Nämnd</th>
                    <th>Kostnadsställe</th>
                    <th>Budgetpost</th>
                    <th>Summa</th>
                </tr>
            </thead>
        {% for expense_part in expense_parts %}
            <tr>
                <td>{{ expense_part.committee_name }}</td>
                <td>{{ expense_part.cost_centre_name }}</td>
                <td>{{ expense_part.budget_line_name }}</td>
                <td>{{ expense_part.amount }}</td>
            </tr>
        {% endfor %}
        </table>
        <br />
        <h2>Verifikationsnummer</h2>
        <input type="text" name="verification" value="{{ expense.verification }}" />
        <br /><br /><br /><br />
        <input type="submit" value="Spara verifikationsnummer" class="button primary-action theme-color btn-color">
    </form>
</div>
{% endblock %}

templates/expenses/payment.html
{% extends "../detail.html" %}
{% load humanize %}

{% block title %}Utbetalning {{ payment.tag }}{% endblock %}

{% block full_content %}

    <div>
        <div>
            <table>
                <thead>
                    <tr>
                        <th colspan="2">Utbetalning {{ payment.tag }}</th>
                    </tr>
                </thead>
                <tr>
                    <th>Mottagare:</th>
                    <td>
                        <a href="{% url 'user-show' payment.receiver.user %}">
                            {{ payment.receiver.user.get_full_name }} ({{ payment.receiver.user.username }}@kth.se)
                        </a>
                    </td>
                </tr>
                <tr>
                    <th>Utbetalningsdatum:</th>
                    <td>{{ payment.date|date:"Y-m-d" }}</td>
                </tr>
                <tr>
                    <th>Utbetalat från konto:</th> 
                    <td>{{ payment.account }}</td>
                </tr>
                <tr>
                    <th>Utbetalat av:</th>
                    <td>
                        <a href="{% url 'user-show' payment.payer.user %}">
                            {{ payment.payer.user.get_full_name }} ({{ payment.payer.user.username }}@kth.se)
                        </a>
                    </td>
                </tr>
                <tr>
                    <th>Summa:</th>
                    <td>{{ payment.amount|intcomma }} kr</td>
                </tr>
            </table>
        </div>

        <h2>Kvitton</h2>
        <table>
            <thead>
                <tr>
                    <th>Beskrivning</th>
                    <th>Belopp</th>
                </tr>
            </thead>
            {% for expense in payment.expense_set.all %}
                <tr>
                    <td><a href="{% url 'expenses-show' expense.id %}">{{ expense.description|capfirst }}</a></td>
                    <td>{{ expense.total_amount|intcomma }} kr</td>
                </tr>
            {% endfor %}


        </table>
    </div>

{% endblock %}

templates/expenses/show.html
{% extends "../detail.html" %}
{% load humanize %}

{% block title %}
    {{ expense.description|capfirst }}
{% endblock %}

{% block action %}
    {% if user.username == expense.owner.user.username %}
        <a href="{% url 'expenses-edit' expense.id %}" class="primary-action">
            Redigera kvitto
        </a>
    {% endif %}
{% endblock %}

{% block full_content %}
<div id="app">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <h2>Kvittodelar</h2>
    <table>
        <thead>
            <tr>
                <th>
                    Belopp
                </th>
                <th>
                    Nämnd
                </th>
                <th>
                    Sekundärt resultatställe
                </th>
                <th>
                    Budgetpost
                </th>
                <th>
                    Attesterad av
                </th>
            </tr>
        </thead>
        <tbody>
        {% for expense_part in expense.expensepart_set.all %}
            <tr>
                <td>
                    <span class="value">{{ expense_part.amount|intcomma }} kr</span>
                </td>
                <td>
                    <a class="value" href="https://budget.datasektionen.se/committees/{{ expense_part.committee_id }}">
                        {{ expense_part.committee_name }}
                    </a>
                </td>
                <td>
                    <span class="value">{{ expense_part.cost_centre_name }}</span>
                </td>
                <td>
                    <span class="value">{{ expense_part.budget_line_name }}</span>
                </td>
                <td>
                    {% if expense_part.attested_by %}
                    <a class="value" href="{% url 'user-show' expense_part.attested_by.user.username %}">
                        {{ expense_part.attested_by.user.get_full_name }} ({{ expense_part.attest_date }})
                    </a>
                    {% else %}
                        {% if expense.owner.user.username != user.username and expense_part.committee_name|lower in user.profile.may_attest %}
                            <span style="display: block;">
                                <form method="POST" action="{% url 'admin-expensepart-attest' expense_part.id %}">
                                    {% csrf_token %}
                                    <button class="pull-right small theme-color btn-color" type="submit" style="margin-right:15px;"><i class="fa fa-check" aria-hidden="true"></i></button>
                                    <span style="margin: 5px 0;display:inline-block;">Du kan attestera &nbsp;</span>
                                </form>
                            </span>
                        {% else %}
                            <span class="value">Ej attesterad</span>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="clear" style="height:50px;"></div>


    <div class="col-sm-6 col-lg-6" style="padding-left: 0;">
        <h2>Information</h2>
        <table>
            <tr>
                <th>Kvitto-id:</th>
                <td>{{ expense.id }}</td>
            </tr>
            <tr>
                <th>Köpt av:</th>
                <td>
                    <a href="{% url 'user-show' expense.owner.user.username %}">
                        {{ expense.owner.user.get_full_name }} ({{ expense.owner.user.username }}@kth.se)
                    </a>
                </td>
            </tr>
            <tr>
                <th>Inköpsdatum:</th>
                <td>
                    {{ expense.expense_date|date:"Y-m-d" }}
                </td>
            </tr>
            <tr>
                <th>Totalsumma:</th>
                <td>
                    {{ expense.total_amount|intcomma }} kr
                </td>
            </tr>
            <tr>
                <th>Registrerat i Cashflow:</th>
                <td>
                    {{ expense.created_date|date:"Y-m-d" }}
                </td>
            </tr>
            <tr>
                <th>Bekräftat i pärmen:</th>
                <td>
                    {% if expense.confirmed_by_id %}
                     {{ expense.confirmed_by.get_full_name }} ({{ expense.confirmed_at }})
                    {% else %}
                    Inte än
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Återbetalat:</th>
                <td>
                    {% if expense.reimbursement %}
                    <a href="{% url 'expenses-payment' expense.reimbursement.id %}">
                        {{ expense.reimbursement.tag }}
                    </a>
                    {% else %}
                    Ej återbetald
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Verifikationsnummer:</th>
                <td>{{ expense.verification|default:"Ej bokförd" }} {% if may_account %}(<a href="{% url 'admin-expense-edit-verification' expense.id %}">Ändra</a>){% endif %}</td>
            </tr>
            <tr>
                <td colspan="2"><a href="{% url 'expenses-delete' expense.id %}"><i class="fa fa-trash"></i> Ta bort kvitto</a></td>
            </tr>
        </table>
    </div>

    <div class="col-sm-6 col-lg-6" style="padding-right: 0;">
        <h2>Filer</h2>
        {% for file in expense.file_set.all %}
        <a href="{{ file.file.url }}">{{ file.file.name }}</a>:<br>
        {% if file.is_image %}
        <a href="{{ file.file.url }}" target="_blank">
            <img class="zoom center-block" style="width: 70%;" src="{{ file.file.url }}" />
        </a>
        {% else %}
        <iframe src="{{ file.file.url }}" style="width:100%;height: 60vh;"></iframe>
        {% endif %}
        <br>
        {% endfor %}
    </div>


    <div class="clearfix"></div>

    <div>
        <h2>Kommentarer</h2>

        <ul class="comments">
            {% for comment in expense.comment_set.all %}
            <li class="clearfix {% if comment.author.user.username == user.username %}own{% endif %}">
                <div class="info">
                    <a v-tooltip="{ content: '{{ comment.author.user.get_full_name }}' }" class="crop" style="background-image:url(https://zfinger.datasektionen.se/user/{{ comment.author.user.username }}/image);" href="/user/{{ comment.author.user.username }}"></a>
                    <span class="name">
                        <a href="{% url 'user-show' comment.author.user.username %}">
                            
                        </a>
                    </span>
                </div>
                <div class="comment" v-tooltip="{ content: 'Skapad {{ comment.date|date:'Y-m-d H:i' }}' }">
                    {{ comment.content }}
                </div>
            </li>
            {% endfor %}
            <li class="new">
                <div class="comment">
                    <form method="POST" id="new" action="{% url 'expenses-comment' expense.id %}">
                        {% csrf_token %}
                        <textarea id="content-field" name="content" rows="3" style="width: 100%;border:none;" placeholder="Skriv en kommentar"></textarea>
                        <button class="pull-right button theme-color btn-color" type="submit">Kommentera</button>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </li>
            <li class="alternatives">
                <h3>Eller skicka en färdig kommentar:</h3>
                <ul>
                    <li><a href="#" v-on:click="send">Jag kan inte hitta ditt utlägg i pärmen. Har du satt in det?</a></li>
                    <li><a href="#" v-on:click="send">Jag attesterar också detta.</a></li>
                    <li><a href="#" v-on:click="send">Det här har jag inte godkänt.</a></li>
                    <li><a href="#" v-on:click="send">Du har angivit större belopp än vad som står på kvittot.</a></li>
                    <li><a href="#" v-on:click="send">Du måste ladda upp både en faktura och ett kontoutdrag.</a></li>
                    <li><a href="#" v-on:click="send">Avvakta med det här utlägget.</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="clearfix"></div>
</div>

<script type="text/javascript">
    new Vue({
        el: '#app', 
        data: function () {
            return {

            }
        },
        methods: {
            send(e) {
                e.preventDefault()
                console.log(e.target.innerHTML)
                document.getElementById('content-field').value = e.target.innerHTML
                document.getElementById('new').submit()
            }
        },
        created() {

        }
    })
</script>
{% endblock %}